defaults: &defaults
  working_directory: ~/thrift-server
  docker:
    - image: circleci/node:6.12.3

version: 2
executorType: machine
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install NPM Dependencies
          command: npm install
      - run:
          name: Run Test Suite
          command: npm test

  publish:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Create .npmrc
          command: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
      - run:
          name: Install NPM Dependencies
          command: npm install
      - run:
          name: Build Publish Assets
          command: npm run build
      - run:
          name: Publish to NPM
          command: npm run release:publish

  publish_fix:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Create .npmrc
          command: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
      - run:
          name: Install NPM Dependencies
          command: npm install
      - run:
          name: Build Publish Assets
          command: npm run build
      - run:
          name: Publish to NPM
          command: npm run release:fixpublish

  prerelease:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Generate .npmrc File
          command: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
      - run:
          name: Install NPM Dependencies
          command: npm install
      - run:
          name: Build Publish Assets
          command: npm run build
      - run:
          name: Publish to NPM
          command: npm run release:prepublish

workflows:
  version: 2
  build_test:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/

      - publish:
          requires:
            - test
          filters:
            tags:
              only: /^(v){1}(0){1}(\.[6]){1}(\.[0-9]+){1}$/
            branches:
              ignore: /.*/

      - publish_fix:
          requires:
            - test
          filters:
            tags:
              only: /^(v){1}(0){1}(\.[0-5]){1}(\.[0-9]+){1}$/
            branches:
              ignore: /.*/

      - prerelease:
            requires:
              - test
            filters:
              tags:
                only: /^(v){1}[0-9]+(\.[0-9]+){2}(-)[0-9]+$/
              branches:
                ignore: /.*/
