defaults: &defaults
  working_directory: ~/thrift-server
  docker:
    - image: circleci/node:6.10.3

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: install-npm
          command: npm install
      - run:
          name: build
          command: npm run build
      - persist_to_workspace:
          root: ./
          # Must be relative path from root
          paths:
            - packages/thrift-client/dist
            - packages/thrift-server-core/dist
            - packages/thrift-server-express/dist
            - packages/thrift-server-hapi/dist
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: install-npm
          command: npm install
      - run:
          name: npm-test
          command: npm test

  publish:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: npm-token
          command: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
      - run:
          name: install-npm
          command: npm install
      - run:
          name: publish-npm
          command: npm run release:publish

workflows:
  version: 2
  build_test:
      jobs:
        - build:
            filters:
              tags:
                only: /.*/
        - test:
            requires:
              - build
            filters:
              tags:
                only: /.*/
        - publish:
            requires:
              - test
            filters:
              tags:
                only: /(v)?[0-9]+(\.[0-9]+)*/
              branches:
                ignore: /.*/
