version: '2'
services:
  vault:
    image: mannimal/vault-cci:latest
    ports:
      - "8200:8200"
      - "8201:8201"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/config.hcl:/vault/config.hcl
